version: '3.8'

services:
  # Discord Bot
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: requiem-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DATABASE_PATH=/app/data/tracking.db
    depends_on:
      - api
    networks:
      - requiem-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # API Backend
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: requiem-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_PATH=/app/data/tracking.db
      - API_HOST=0.0.0.0
      - API_PORT=8000
    networks:
      - requiem-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: requiem-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_DEFAULT_GUILD_ID=${DISCORD_GUILD_ID}
    depends_on:
      - api
    networks:
      - requiem-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  requiem-data:
    driver: local

networks:
  requiem-network:
    driver: bridge
